### ISSUE TITLE
UK Needs province

### ISSUE THREAD

**Issue by GadgetSteve** [ryanss/python-holidays#40]
Currently the United Kingdom has no province/state member but there are different bank holidays between the countries that make up the UK.

Specifically with E=England, W=Wales, S=Scotland, N=Northern Ireland, R=Republic of Ireland & M=Isle of Man and with all holidays movable to the next working day in the case of not falling on a working day:

 - 1 January (New Year's Day) - EWSNRM
 - 2 January - S
 - 17 March (St Patrick's Day) - NR
 - The Friday before Easter Sunday (Good Friday) - EWSN M
 - The Monday after Easter Sunday (Easter Monday) - EW NRM
 - First Monday in May[2][3] (May Day, Early May Bank Holiday) - EWSNRM
 - Last Monday in May[4][5] (Spring Bank Holiday) - EWSN M
 - First Monday in June (June Bank Holiday) - R
 - First Friday in June (TT Bank Holiday) - M
 - 5 July (Tynwald Day) - M
 - 12 July (The Twelfth, Battle of the Boyne) - N		
 - First Monday in August (Summer Bank Holiday) - S R
 - Last Monday in August (Late Summer Bank Holiday, August Bank Holiday) - EW N M
 - Last Monday in October (October Bank Holiday) - R
 - 30 November (St Andrew's Day) - S		
 - 25 December (Christmas Day) - EWSNRM
 - 26 December (Boxing Day, St Stephen's Day) - EWSNRM

The really confusing one is that if Christmas day falls on a weekend day it is move to the day after Boxing Day so that if the 25th is Saturday then Boxing Day will be moved from Sunday to Monday and Christmas Day will have a substitute day on the 28th.

Please consider adding these regions with their specific holidays to this tool

**Comment by ryanss** [comment]
I added the individual countries separately as they are countries and not provinces. If you could take a look at the new additions and let me know if you see any problems that would be terrific, thanks!

```python
holidays.England()
holidays.Wales()
holidays.Scotland()
holidays.NorthernIreland()
holidays.Ireland()
holidays.IsleOfMan()
```

**Comment by ryanss** [comment]
Here is an attempt at adding qualifiers to the holiday names (only when generated with `holidays.UnitedKingdom()` or `holidays.UK()`). What do you think of this?

```python
>>> import holidays
>>> for date, name in sorted(holidays.UK(years=2016).items()):
...     print date, name
... 
'2016-01-01' New Year's Day
'2016-01-02' New Year Holiday [Scotland]
'2016-01-04' New Year Holiday [Scotland] (Observed)
'2016-03-17' St. Patrick's Day [Northern Ireland]
'2016-03-25' Good Friday
'2016-03-28' Easter Monday [England, Wales, Northern Ireland]
'2016-05-02' May Day
'2016-05-30' Spring Bank Holiday
'2016-07-12' Battle of the Boyne [Northern Ireland]
'2016-08-01' Summer Bank Holiday [Scotland]
'2016-08-29' Late Summer Bank Holiday [England, Wales, Northern Ireland]
'2016-11-30' St. Andrew's Day [Scotland]
'2016-12-25' Christmas Day
'2016-12-26' Boxing Day
'2016-12-27' Christmas Day (Observed)
>>> 
```

**Comment by GadgetSteve** [comment]
Looks good!

**Comment by ryanss** [comment]
Great, thanks for the help on this!
