### ISSUE TITLE
Problem with travis?

### ISSUE THREAD

**Issue by willhardy** [ryanss/python-holidays#56]
It appears that there is a problem with the build configuration. `pip install $DATEUTIL` fails on Python 3.2 (and therefore also pypy3). This may be because `pip>=8.0.0` no longer supports python 3.2.

See eg https://travis-ci.org/ryanss/python-holidays/jobs/232419470

**Comment by willhardy** [comment]
I imagine it would be easiest to drop Python 3.2, it's no longer supported.

**Comment by hugovk** [comment]
Here's a PR to drop Python 3.2: https://github.com/ryanss/python-holidays/pull/78.

**Comment by dr-prodigy** [comment]
Fixed in **1452cc3**
