### ISSUE TITLE
Reformationstag Germany

### ISSUE THREAD

**Issue by julian5678** [ryanss/python-holidays#68]
Reformationstag 31.10. is always a public holiday in Germanys state Brandenburg (BR)
Furthermore in 2017 it is a public holiday in all states (500. Anniversary of Martin Luthers 95 Thesis)

**Comment by venthur** [comment]
Brandenburg is BB and not BR and BB is already in the list. The 2017 issue is correct though.

**Comment by dr-prodigy** [comment]
Fixed in **1452cc3**
